# Generated by Django 5.0.7 on 2024-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_disprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='disprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price'),
        ),
    ]
