# Generated by Django 5.0.7 on 2024-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.size'),
        ),
    ]
