# Generated by Django 5.0.7 on 2024-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_size_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='shop.color'),
        ),
    ]
